# 工作流名称
name: Build Serial-Studio for Windows

# 工作流的触发条件
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-windows:
    # 直接指定运行环境为最新的 Windows Server
    runs-on: windows-latest

    steps:
      # 第一步：检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 第二步：安装 Qt 环境（包含 Graphs 组件）
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.9.1'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
          cache: 'true'
          modules: 'qtgraphs'

      # (新增) 第三步：验证 Qt 环境变量
      # 这个步骤用来打印 QT_DIR 的值，以确认它已被正确设置
      - name: Verify Qt Environment
        run: |
          echo "QT_DIR is set to: ${{ env.QT_DIR }}"
          echo "Listing contents of QT_DIR:"
          dir "${{ env.QT_DIR }}"
        shell: pwsh # 使用 PowerShell 以获得更一致的跨平台体验

      # 第四步：配置 CMake
      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake .. -DQt6_DIR=${{ env.QT_DIR }}/lib/cmake/Qt6 -DCMAKE_BUILD_TYPE=Release -G "Ninja"

      # 第五步：执行编译
      - name: Build with CMake
        run: |
          cd build
          cmake --build . --config Release

      # 第六步：上传编译产物
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: serial-studio-windows
          path: |
            build/bin/Release/Serial-Studio.exe
            build/bin/Release/*.dll